# Generated by Django 6.0.2 on 2026-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_paid_amount_booking_transaction_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[("OPEN", "Open Booking"), ("CLOSED", "Closed Booking")],
                default="CLOSED",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="current_players",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="open_game_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="booking",
            name="required_players",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
