# Generated by Django 6.0.2 on 2026-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_booking_type_booking_current_players_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("PAY_DEPOSIT", "Pay on Field"),
                    ("PAY_FULL_ONLINE", "Pay Full Online"),
                ],
                default="PAY_DEPOSIT",
                max_length=20,
            ),
        ),
    ]
