# Generated by Django 6.0.2 on 2026-04-16 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_payment_mode"),
        ("grounds", "0003_groundavailability_groundblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="uniq_booking_slot",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("ground", "date", "start_time", "end_time"),
                name="uniq_active_booking_slot",
            ),
        ),
    ]
