# Generated by Django 6.0.2 on 2026-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ground",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ground",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="ground",
            name="phone",
            field=models.CharField(blank=True, default="No description", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ground",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
