# Generated by Django 6.0.2 on 2026-02-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0002_alter_ground_description_alter_ground_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ground",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="grounds.ground",
                    ),
                ),
            ],
            options={
                "ordering": ["ground", "day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["ground", "day_of_week", "start_time"],
                        name="grounds_gro_ground__e0acaa_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="availability_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GroundBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ground",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="grounds.ground",
                    ),
                ),
            ],
            options={
                "ordering": ["ground", "date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["ground", "date", "start_time"],
                        name="grounds_gro_ground__937f82_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="block_end_after_start",
                    )
                ],
            },
        ),
    ]
