# Generated by Django 6.0.2 on 2026-04-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionnotification",
            name="connection_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="connections.connectionrequest",
            ),
        ),
        migrations.AlterField(
            model_name="connectionnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REQUEST_SENT", "Request Sent"),
                    ("REQUEST_ACCEPTED", "Request Accepted"),
                    ("REQUEST_REJECTED", "Request Rejected"),
                    ("BOOKING_CANCELLED", "Booking Cancelled"),
                ],
                max_length=30,
            ),
        ),
    ]
