# Generated by Django 6.0.2 on 2026-04-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "connections",
            "0002_alter_connectionnotification_connection_request_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REQUEST_SENT", "Request Sent"),
                    ("REQUEST_ACCEPTED", "Request Accepted"),
                    ("REQUEST_REJECTED", "Request Rejected"),
                    ("BOOKING_REQUEST", "Booking Request"),
                    ("BOOKING_CANCELLED", "Booking Cancelled"),
                ],
                max_length=30,
            ),
        ),
    ]
